#! /bin/sh

# Startup programs
~/.config/bspwm/startup &

# Workspaces
ws1="web"
ws2="dev"
ws3="ter"
ws4="dir"
ws5="cg"
ws6="vm"
ws7="other"

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7

# Window config
bspc config border_width 1
bspc config window_gap 0
bspc config focus_follows_pointer false
bspc config focused_border_color "#3F85BF"
bspc config normal_border_color "#5c6370"

# Layout config
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Assigning workspaces
bspc rule -a "Code" desktop='^2'
bspc rule -a "firefox" desktop='^1'
bspc rule -a "kdenlive" desktop='^5'
bspc rule -a "VirtualBox Manager" desktop='^6'
bspc rule -a "Virt-manager" desktop='^6'
bspc rule -a "ru-turikhay-tlauncher-bootstrap-Bootstrap" desktop='^7'
bspc rule -a "Minecraft 1.17.1" desktop='^7'

# Making windows floating
bspc rule -a "Preferences" state=floating
bspc rule -a "obs" state=floating
bspc rule -a "ru-turikhay-tlauncher-bootstrap-Bootstrap" state=floating

