#! /bin/sh

# Startup programs
~/.config/bspwm/startup &

# Workspaces
# ws1="  "
# ws2="  "
# ws3="  "
# ws4="  "
# ws5="  "
# ws6="  "
# ws7="  "
# ws8="other"

ws1="web"
ws2="dev"
ws3="ter"
ws4="dir"
ws5="cg"
ws6="vm"
ws7="music"
ws8="other"

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8

# Window config
bspc config border_width 2
bspc config window_gap 20
bspc config focus_follows_pointer false
bspc config focused_border_color "#4D525C"
bspc config normal_border_color "#3E424A"

# Layout config
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false

# Assigning workspaces
bspc rule -a "firefox" desktop='^1' focus=on
bspc rule -a "Code" desktop='^2'
bspc rule -a "jetbrains-idea-ce" desktop='^2'
bspc rule -a "kdenlive" desktop='^5'
bspc rule -a "Natron" desktop='^5'
bspc rule -a "VirtualBox Manager" desktop='^6'
bspc rule -a "Virt-manager" desktop='^6'
bspc rule -a "Audacious" desktop='^7'
bspc rule -a "org-tlauncher-tlauncher-rmo-TLauncher" desktop='^8'
bspc rule -a "Minecraft* 1.17.1" desktop='^8'

# Making windows floating
bspc rule -a "Preferences" state=floating
bspc rule -a "obs" state=floating
bspc rule -a "ru-turikhay-tlauncher-bootstrap-Bootstrap" state=floating

