#!/bin/bash

pgrep -x lemonbar > /dev/null || panel &
sleep 0.3
#pgrep -x trayer > /dev/null || trayer \
																	#--edge top \
																	#--align right \
																	#--distancefrom right \
																	#--distance 0 \
																	#--padding 3 \
																	#--SetDockType true \
																	#--SetPartialStrut true \
																	#--expand true \
																	#--monitor VGA1 \
																	#--tint 0x33373DFF \
																	#--widthtype request \
																	#--heighttype pixel \
																	#--height 20 \
																	#--transparent false \
																	#--alpha 0 \
																	#--iconspacing 0 &
pgrep -x stalonetray > /dev/null || stalonetray \
																		 --background "#282C34" \
																		 --icon-size 14 \
																		 --geometry 2x1-7+7 \
																		 --grow-gravity E \
																		 --icon-gravity E \
																		 --kludges force_icons_size &
