#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  pactl -- set-sink-volume 0 +5%; pkill -SIGRTMIN+10 i3blocks
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  pactl set-sink-mute 0 toggle; pkill -SIGRTMIN+10 i3blocks
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  pactl -- set-sink-volume 0 -5%; pkill -SIGRTMIN+10 i3blocks
fi

VOLUME_MUTE="MUTED"
VOLUME_LOW=""
VOLUME_MID=""
VOLUME_HIGH=""
SOUND_LEVEL=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
MUTED=$(pactl list sinks | awk '/Mute/ { print $2 }')

ICON=$VOLUME_MUTE

if [ "$MUTED" = "yes" ]
then
    ICON="$VOLUME_MUTE"
else
    if [ "$SOUND_LEVEL" -lt 34 ]
    then
        ICON="$VOLUME_LOW"
    elif [ "$SOUND_LEVEL" -lt 67 ]
    then
        ICON="$VOLUME_MID"
    else
        ICON="$VOLUME_HIGH"
    fi
fi

if [ "$MUTED" = "yes" ]
then
    echo "$VOLUME_MUTE"
else
    echo "$ICON $SOUND_LEVEL%"
fi
